services:
  - type: web
    name: deepfake-detection
    env: python
    plan: free  # or your specific plan
    pythonVersion: "3.10.11"
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py  # or your specific start command
